### PR TITLE
Upload: switch to dcplib version of get_s3_multipart_chunk_size

### PR DESCRIPTION
**Pull request by sampierson**
Upload: switch to dcplib.s3_multipart version of get_s3_multipart_chunk_size

### CODE REVIEW

**Comment by mweiden** [comment]
Ah! @sampierson we were working on the same thing: https://github.com/HumanCellAtlas/dcp-cli/pull/150

**Comment by sampierson** [comment]
I know.  I did this yesterday.  I made @ttung a reviewer before he filed his ticket.
My solution was incomplete though.   Looks like yours has more coverage.

**Comment by sampierson** [comment]
Withdrawing this PR as Matt's #150 has better coverage of the issue.

**Comment by ttung** [comment]
My apologies, I flubbed this. :(

**Pull request closed without merging**
