### PR TITLE
IAM-Not: get temporary aws credentials on demand

### PR DESCRIPTION
**Pull request by sampierson**
instead of using IAM user for each upload area

Described in document: https://docs.google.com/document/d/1JFO75A9OR1gnCT1nYHH5p-vEaf0-TdOtOme3M3b9g3A/edit#

Paired with https://github.com/HumanCellAtlas/upload-service/pull/100

### CODE REVIEW

**Comment by sampierson** [comment]
Note for reviewers, the real meat of this PR is in commit https://github.com/HumanCellAtlas/dcp-cli/pull/126/commits/1f158df916c8c49ff266e9dfd23537c6a3c4d6b9 "upload: commands now take a URI instead of URN".  Everything else is refactoring.

**Comment by sampierson** [comment]
@kislyuk what do you dislike about responses?

**Comment by kislyuk** [comment]
I prefer to mock things more directly by monkeypatching or other means instead of using external dependencies. Also, @hannes-ucsc identified some issues with the reliability of the responses decorator's cleanup logic.

**Comment by hannes-ucsc** [comment]
https://github.com/HumanCellAtlas/dcp-cli/issues/127

Cost me a day.

**Pull request merged**
