### PR TITLE
Updating boto3 version

### PR DESCRIPTION
**Pull request by maniarathi**
Previous 1.7-1.8 requirement is incompatible with upload service. Also alphabetized the dependencies.

### CODE REVIEW

**Comment by xbrianh** [comment]
@parthshahva Is Upload prepared for this boto3 version bump?

**Comment by sampierson** [comment]
@xbrianh yes Upload is the one initiating this

**Comment by parthshahva** [comment]
@maniarathi @sampierson The upgrade of boto3 breaks the use of mock in our tests, leading to a slate of permission denied errors on CreateBucket. We'll need to fix our tests before merging this in.

**Comment by kislyuk** [comment]
Only direct package dependencies (those imported by the library) should be listed here. Dependencies should manage their sub-dependencies.

**Pull request merged**
