### PR TITLE
Retry on read errors.

### PR DESCRIPTION
**Pull request by ttung**

### CODE REVIEW

**Comment by briandoconnor** [comment]
@ttung are there any other places in the code base that the retry policy needs to be tweaked or is this it?

**Comment by ttung** [comment]
> @ttung are there any other places in the code base that the retry policy needs to be tweaked or is this it?

shouldn't be.

**Comment by ttung** [comment]
We may need to tweak the retry policy more as we see what kind of errors we encounter / how often we encounter them.

**Comment by kislyuk** [comment]
Released in v3.4.2, please test.

**Pull request merged**
