### PR TITLE
Avoid version conflict by pinning docutils (#418)

### PR DESCRIPTION
**Pull request by jessebrennan**

### CODE REVIEW

**Comment by kislyuk** [comment]
> I think the CLI should always pin dependencies.

The CLI is liable to be installed alongside other Python libraries, increasing the likelihood of unsatisfiable pins if another package also depends on a pinned version of the same package.

For this reason libraries should range their dependencies as loosely as reasonable beyond the major version number.

@jessebrennan can you please describe the version conflict that occurred here, or link to a relevant issue?

**Comment by jessebrennan** [comment]
@kislyuk it's issue #418. I linked it to the PR and referenced it in the PR title and commit.

**Comment by kislyuk** [comment]
Thanks, sorry I missed that. LGTM

**Comment by hannes-ucsc** [comment]
> The CLI is liable to be installed alongside other Python libraries, increasing the likelihood of unsatisfiable pins if another package also depends on a pinned version of the same package.

> For this reason libraries should range their dependencies as loosely as reasonable beyond the major version number.

In my experience, this approach doesn't work in practice, simply because "as loosely as reasonable" is ill-defined and unreliable. Any package can potentially break on any update of a dependency, even minor ones. This problem is the reason virtual environments were invented, and it's the reason why other languages use the share-nothing approach to package management, most prominently Node, Go and Rust.

**Pull request merged**
